version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.15-alpine
    container_name: "yunplus-io-nginx"
    ports:
      - 8080:80
      - 8099:8099
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/letsencrypt:/etc/letsencrypt
    environment:
      TZ: "Asia/Shanghai"
    extra_hosts:
      - "myhost:10.9.184.52"
    networks:
      - yunplus-network

    # not need
  # registry:
  #   image: 'registry:2.1.1'
  #   container_name: "registry"
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     TZ: "Asia/Shanghai"
  #   volumes:
  #     - /opt/registry:/var/lib/registry
  #   networks:
  #     - yunplus-network
  #   restart: always
  db:
    image: "mysql:5.6"
    container_name: "fpm-mysql-server"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./mysqldata/:/var/lib/mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - yunplus-network
    restart: always

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "yunplus-io-phpmyadmin"
    ports:
      - "88:80"
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      - "db"
    networks: 
      - yunplus-network
    restart: always

  mongo:
    image: 'mongo:3.4.20'
    container_name: "yunplus-io-mongo-server"
    restart: always
    volumes:
      - ./backup/:/backup/
    ports:
      - 27017:27017  
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    networks:
      - yunplus-network

    # cant run
  # manager:
  #   # mongodb://admin:admin@mongo
  #   image: 'mrvautin/adminmongo'
  #   container_name: "yunplus-io-mongo-admin"
  #   restart: always
  #   ports:
  #     - 5234:1234
  #   environment:
  #     CONN_NAME: 'manager'
  #     DB_USERNAME: 'admin'
  #     DB_PASSWORD: 'admin'
  #     DB_HOST: 'mongo'
  #     DB_PORT: 27017
  #   depends_on:
  #     - 'mongo'
  #   networks:
  #     - yunplus-network

networks:
  yunplus-network: 